### ISSUE TITLE
to-do: @maeyoung

### ISSUE THREAD

**Issue by to-besomeone** [maeyoung/news-crawling#1]
1. refactoring `LATimes_sel.py` from @to-besomeone code to @maeyoung code
2. **should- convert searching part in LA Times sites to Google**
3. duration: 2010 - 2020
4. site: www.latimes.com
5. query: `site:www.latimes.com 2010..2020 korea`

**Comment by maeyoung** [comment]
complete to convert searching url part in LATimes_sel.py to use google searching site.
